import process from 'process';
import builtins from 'builtin-modules';
import * as esbuild from 'esbuild';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === 'production';

const buildOptions = {
  banner: {
    js: banner,
  },
  bundle: true,
  entryPoints: ['main.ts'],
  external: [
    'obsidian',
    'electron',
    '@codemirror/autocomplete',
    '@codemirror/collab',
    '@codemirror/commands',
    '@codemirror/language',
    '@codemirror/lint',
    '@codemirror/search',
    '@codemirror/state',
    '@codemirror/view',
    '@lezer/common',
    '@lezer/highlight',
    '@lezer/lr',
    ...builtins,
  ],
  format: 'cjs',
  logLevel: 'info',
  outfile: 'dist/main.js',
  sourcemap: prod ? false : 'inline',
  target: 'es2018',
  treeShaking: true,
  // minify: true,
};

if (prod) {
  await esbuild.build(buildOptions);
  process.exit(0);
} else {
  const devBuild = await esbuild.build({
    ...buildOptions,
    metafile: true,
  });

  console.log(await esbuild.analyzeMetafile(devBuild.metafile));
}
