CREATE TABLE `ZAEANNOTATION` (
	`ZANNOTATIONASSETID` text,
	`ZFUTUREPROOFING5` text,
	`ZANNOTATIONREPRESENTATIVETEXT` text,
	`ZANNOTATIONSELECTEDTEXT` text NOT NULL,
	`ZANNOTATIONLOCATION` text,
	`ZANNOTATIONNOTE` text,
	`ZANNOTATIONCREATIONDATE` integer,
	`ZANNOTATIONMODIFICATIONDATE` integer,
	`ZANNOTATIONSTYLE` integer,
	`ZANNOTATIONDELETED` integer
);
--> statement-breakpoint
CREATE TABLE `ZBKLIBRARYASSET` (
	`ZASSETID` text,
	`ZTITLE` text,
	`ZAUTHOR` text,
	`ZGENRE` text,
	`ZLANGUAGE` text,
	`ZLASTOPENDATE` integer,
	`ZDATEFINISHED` integer,
	`ZCOVERURL` text
);
