// export const BOOKDBNAME = 'test-BKLibrary.sqlite';
export const BOOKS_DB_NAME = 'empty-BKLibrary.sqlite';
// export const BOOKS_DB_NAME = 'test-BKLibrary-copy.sqlite';
export const BOOKS_LIBRARY_NAME = 'ZBKLIBRARYASSET';
export const BOOKS_LIBRARY_COLUMNS = [
	'ZASSETID',
	'ZTITLE',
	'ZAUTHOR',
	'ZGENRE',
	'ZLANGUAGE',
	'ZLASTOPENDATE',
	'ZCOVERURL'
];
export const HIGHLIGHTS_DB_NAME = 'test-AEAnnotation_v10312011_1727_local.sqlite';
export const HIGHLIGHTS_LIBRARY_NAME = 'ZAEANNOTATION';

export const HIGHLIGHTS_LIBRARY_COLUMNS = [
	'ZANNOTATIONASSETID',
	'ZFUTUREPROOFING5',
	'ZANNOTATIONREPRESENTATIVETEXT',
	'ZANNOTATIONSELECTEDTEXT',
	'ZANNOTATIONNOTE',
	'ZANNOTATIONCREATIONDATE',
	'ZANNOTATIONMODIFICATIONDATE',
	'ZANNOTATIONSTYLE'
];
